Correct number of syllables on first line of haiku
do-community/cloud_haiku pull request #1193
Opened 2020-10-21 14:55 UTC by deepyaman

No matter how I read it, I couldn't reconcile the original first line to 5 syllables.

An alternative fix would be `SARS Covid19`, but the proposed correction is more common when starting with `SARS`.

2020-10-22 14:17 UTC, deepyaman commented on _haikus/please_go_away_covid.md
> +SARS-CoV-2 virus<br>
```suggestion
SARS-CoV-two virus<br>
```

2020-10-26 00:10 UTC, ltagliaferri requested changes
Thank you for your interest in Cloud Haiku! Please submit one new, original haiku in markdown format in order to contribute. Edits on existing haikus do not count as a contribution. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) for more guidance on how to create a valid pull request.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2020-10-26 14:13 UTC, deepyaman commented
@ltagliaferri Thank you for your comment. I'm not interested in this from a contribution count perspective; I already have more than enough PRs for Hacktoberfest:

![image](https://user-images.githubusercontent.com/14007150/97182716-428ac280-1773-11eb-8c5d-fc3540158f58.png)

I want to fix this because I don't believe it is a valid haiku. Should I just ignore this and try fixing number handling in https://github.com/words/syllable for the future instead?

2020-10-27 01:29 UTC, ltagliaferri commented
Sure, working on a syllable counter sounds good to me! The reason why we don't want others to edit others' file doesn't have to do with Hacktoberfest, but that we want each author to have control over the text. Thank you.

2020-10-27 01:29 UTC, closed without merging