Added an omnipresent haiku
do-community/cloud_haiku pull request #1448
Opened 2021-09-25 11:35 UTC by rajatshenoy56

2021-09-26 18:51 UTC, ltagliaferri requested changes
Thank you for submitting this haiku! There are some changes that need to be made to the syllable count in order to have a valid haiku. The test suite on our haiku will let you know which lines are failing, please check the **details** under "All checks have failed" of this pull request to figure out which lines need to be modified.

A haiku is composed of 3 lines. The first line is 5 syllables long, the second line is 7 syllables long, and the third line is 5 syllables long. Although the majority of the haikus here are written in English, you can submit a haiku in any human language.

Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2021-09-26 18:51 UTC, ltagliaferri commented on _haikus/omnipresent.md
> +child" the cloud replied.<br>
This last line is one syllable too long. You can try:

```
child," Cloud replied.<br>
```

2021-09-27 06:02 UTC, rajatshenoy56 commented
The last line of the haiku was updated

2021-09-28 16:51 UTC, ltagliaferri approved these changes
Awesome, thank you for the update and for contributing to open source 🎉

2021-09-28 16:51 UTC, merged

2021-09-28 17:02 UTC, rajatshenoy56 commented
Thank you so much!