'haiku'
do-community/cloud_haiku pull request #1980
Opened 2022-10-01 09:48 UTC by Anandbrewery

Thanks! for reading my pull request

2022-10-01 15:25 UTC, Anandbrewery commented
hey  please can i know why my pull request is not accepted

2022-10-07 20:33 UTC, ltagliaferri requested changes
Thanks for your interest in this repository. We would like contributors to provide an original haiku. Please refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2022-10-07 20:33 UTC, ltagliaferri commented on _haikus/2022hacktoberfest_Anand.md
> +author:Anandbrewery
Add a space to format the header correctly

```suggestion
author: Anandbrewery
```

2022-10-08 05:19 UTC, Anandbrewery commented
@ltagliaferri  please do check now i have updated

2022-10-08 18:59 UTC, ltagliaferri requested changes
Thanks for your interest in this repository. We would like contributors to provide an original haiku. Please refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2022-10-10 13:59 UTC, ltagliaferri commented
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request. 

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2022-10-10 13:59 UTC, closed without merging