Suraj kumar haiku
do-community/cloud_haiku pull request #1995
Opened 2022-10-01 13:54 UTC by Surajkumar98012

thanks for reading my pull request

2022-10-03 21:51 UTC, ltagliaferri requested changes
Thank you for submitting this haiku! There are some changes that need to be made to the syllable count in order to have a valid haiku.

A haiku is composed of 3 lines. The first line is 5 syllables long, the second line is 7 syllables long, and the third line is 5 syllables long. Although the majority of the haikus here are written in English, you can submit a haiku in any human language.

Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2022-10-04 11:00 UTC, Surajkumar98012 commented
Ok I will edit it today

2022-10-07 20:40 UTC, ltagliaferri requested changes
Suggesting these changes for the syllables to be correct

2022-10-07 20:40 UTC, ltagliaferri commented on _haikus/2022_opensource.md
> +i am a beginner<br>
```suggestion
i'm a beginner<br>
```

2022-10-07 20:40 UTC, ltagliaferri commented on _haikus/2022_opensource.md
> +in the field of an open source<br>
```suggestion
in the field of open source<br>
```

2022-10-07 20:40 UTC, ltagliaferri commented on _haikus/2022_opensource.md
> +happy to contribute<br>
```suggestion
glad to contribute<br>
```

2022-10-08 19:04 UTC, ltagliaferri approved these changes
Thank you for this haiku and for contributing to open source 🎉

2022-10-08 19:04 UTC, merged