subhagata haiku
do-community/cloud_haiku pull request #2357
Opened 2022-10-10 17:49 UTC by subhagataa

thank you for reading my pull request :)

2022-10-21 04:00 UTC, ltagliaferri requested changes
The formatting is not quite right here, I made the suggested edits, can you re-commit?

2022-10-21 04:00 UTC, ltagliaferri commented on _haikus/2022_my first haiku.md
> +---
```suggestion
```

2022-10-21 10:26 UTC, subhagataa commented
How do I re-commit? I clicked those commit  buttons..and resolved the
conversation. Is that it?


On Fri, Oct 21, 2022 at 9:31 AM ltagliaferri ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> The formatting is not quite right here, I made the suggested edits, can
> you re-commit?
> ------------------------------
>
> In _haikus/2022_my first haiku.md
> <https://github.com/do-community/cloud_haiku/pull/2357#discussion_r1001340069>
> :
>
> > @@ -0,0 +1,10 @@
>
> +---
>
> +layout: haiku
>
> +title: my first haiku
>
> +author: subhagata
>
> +
>
>
> ⬇️ Suggested change
>
> -
>
> +---
>
>
> ------------------------------
>
> In _haikus/2022_my first haiku.md
> <https://github.com/do-community/cloud_haiku/pull/2357#discussion_r1001340247>
> :
>
> > @@ -0,0 +1,10 @@
>
> +---
>
> +layout: haiku
>
> +title: my first haiku
>
> +author: subhagata
>
> +
>
> +It's my first haiku
>
> +I don't even know what to write
>
> +I am still thinking
>
> +
>
> +---
>
>
> ⬇️ Suggested change
>
> ----
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/do-community/cloud_haiku/pull/2357#pullrequestreview-1150296021>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3HOM3OJ4JF5C6N2SBXKOCTWEIIP5ANCNFSM6AAAAAARBRXPRM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-22 17:31 UTC, ltagliaferri commented on _haikus/2022_my first haiku.md
> +I don't even know what to write
Awesome, you re-committed! This line needs one fewer syllable, maybe like this: 

```suggestion
I do not know what to write
```

2022-10-23 09:28 UTC, subhagataa commented
done, thank you

2022-10-29 02:21 UTC, ltagliaferri approved these changes
Thank you for this haiku and for contributing to open source 🎉

2022-10-29 02:21 UTC, merged