Added a haiku
do-community/cloud_haiku pull request #2395
Opened 2022-10-12 01:39 UTC by aemolinas

2022-10-12 01:43 UTC, aemolinas commented
Please add hacktoberfest-accepted to this PR.

2022-10-21 04:34 UTC, ltagliaferri requested changes
The extra line is going to mess up our continuous verification, can you remove it, please?

2022-10-21 04:34 UTC, ltagliaferri commented on _haikus/microservice.md
> +# Microservice
```suggestion
```

2022-10-21 23:52 UTC, aemolinas commented
I removed the extra spaces in the file. I hope I did this correctly. please let me know if I did not.

2022-10-22 17:29 UTC, ltagliaferri approved these changes
Thank you for this haiku and for contributing to open source 🎉

2022-10-22 17:29 UTC, merged

2022-10-25 02:32 UTC, aemolinas commented
If possible I would like to use this as my first submission for Hactoberfest. Would you be willing to add the label hacktoberfest-accepted to this PR, please?

2022-10-25 02:34 UTC, ltagliaferri commented
With the merge it counts as a hacktoberfest contribution

2022-10-25 03:52 UTC, aemolinas commented
Thank you so much!

On Mon, Oct 24, 2022 at 9:34 PM ltagliaferri ***@***.***>
wrote:

> With the merge it counts as a hacktoberfest contribution
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/do-community/cloud_haiku/pull/2395#issuecomment-1289896050>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKUYGXNNHRSNW6JMRIITYLWE5BMNANCNFSM6AAAAAARCZ7TGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>