Added new haiku named 2022_nevena_haiku
do-community/cloud_haiku pull request #2433
Opened 2022-10-13 08:54 UTC by nverbic

Added  a new haiku as part of the event " Introduction to Hacktoberfest 2022 and Open Source Contributions" organized by Women Who Code Python community.

2022-10-22 18:06 UTC, ltagliaferri requested changes
Thank you for coming to the Women Who Code event! It looks like you need to remove a syllable each from the first line and the last line. I made a suggestion, can you re-commit with an update so I can merge? Thank you!

2022-10-22 18:06 UTC, ltagliaferri commented on _haikus/2022_nevena_haiku.md
> +Programming languages.<br>
```suggestion
Programming language.<br>
```

2022-10-22 18:06 UTC, ltagliaferri commented on _haikus/2022_nevena_haiku.md
> +together, in the clouds?<br>
```suggestion
together, in clouds?<br>
```

2022-10-24 09:54 UTC, nverbic commented
Hi, thank you for your review. I have commited your suggestions. I am not sure whether this is enough for you to merge the changes into the main branch. I am also a little bit worried about the "All checks have failed" (@github-actions
PR tests / test (pull_request_target) Failing after 12s)  notification that I can see under this pull request.  Should I run some tests before performing a pull request? 

Thank you!
Br
Nevena

2022-10-31 19:48 UTC, ltagliaferri approved these changes
Thank you for this haiku and for contributing to open source 🎉

2022-10-31 19:48 UTC, merged