Create aakarshan_haiku.md
do-community/cloud_haiku pull request #2597
Opened 2022-10-20 02:24 UTC by aakarshank

first Hacktoberfest pull request

2022-10-25 21:52 UTC, ltagliaferri requested changes
Can you fix the formatting issue in the header please? Thank you

2022-10-25 21:52 UTC, ltagliaferri commented on _haikus/aakarshan_haiku.md
> +author:aakarshank
```suggestion
author: aakarshank
```

2022-10-26 11:25 UTC, aakarshank reviewed
Changed the formatting

2022-11-01 05:21 UTC, ltagliaferri commented on _haikus/aakarshan_haiku.md
> +title:Aakarshan Haiku
```suggestion
title: Aakarshan Haiku
```

2022-11-01 05:21 UTC, ltagliaferri commented on _haikus/aakarshan_haiku.md
> +layout:haiku
```suggestion
layout: haiku
```

2022-11-01 05:21 UTC, merged