Create 2023_tech_tackle.md
do-community/cloud_haiku pull request #2887
Opened 2023-10-02 10:08 UTC by akhil-maker

Added a new haiku

2023-10-09 03:04 UTC, ltagliaferri requested changes
Thank you for submitting this haiku! There are some changes that need to be made to the syllable count in order to have a valid haiku. 

A haiku is composed of 3 lines. The first line is 5 syllables long, the second line is 7 syllables long, and the third line is 5 syllables long. Although the majority of the haikus here are written in English, you can submit a haiku in any human language. **Verify your haiku syllables with a checker like [Haiku Syllable Counter](https://www.haikusyllablecounter.com/)**.

Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

2023-10-09 18:27 UTC, akhil-maker commented
@ltagliaferri I have made the changes as you suggested, 5 syllables in 1st, 7 in second and 5 in third line

2023-10-11 03:23 UTC, ltagliaferri requested changes

2023-10-11 03:23 UTC, ltagliaferri commented on _haikus/2023_tech_tackle.md
> +Stuck while coding and programming<br>
```suggestion
Stuck while coding and <br>
```

2023-10-11 03:23 UTC, ltagliaferri commented on _haikus/2023_tech_tackle.md
> +Get your programmer's duck to discuss problems<br>
```suggestion
programming. Get your duck to<br>
```

2023-10-11 03:23 UTC, ltagliaferri commented on _haikus/2023_tech_tackle.md
> +Get a clean solved code <br>
```suggestion
 discuss the problems<br>
```

2023-10-11 16:39 UTC, akhil-maker commented
@ltagliaferri Committed the suggestions made by you. Hope they are correct now.

2023-10-16 03:49 UTC, ltagliaferri approved these changes
Thank you for this haiku and for contributing to open source 🎉 🦆

2023-10-16 03:49 UTC, merged