added Initial_moon haiku
do-community/cloud_haiku pull request #898
Opened 2020-10-09 17:33 UTC by Lucatake

my first pull

2020-10-11 16:45 UTC, ltagliaferri requested changes
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

2020-10-14 14:57 UTC, ltagliaferri requested changes
Thanks for updating the haiku! Can you remove the `coding.md` file from this pull request? Thank you!

2020-10-14 15:12 UTC, Lucatake commented
> 
> 
> Thanks for updating the haiku! Can you remove the `coding.md` file from this pull request? Thank you!

How can I do that?

2020-10-16 22:53 UTC, ltagliaferri commented
Hi @Lucatake, there are a few ways to do that. The easiest way I think would be to save your `Initial_moon.md` file somewhere else on your computer, delete the `cloud_haiku` repo from your computer, and then update and clone the repo again (taking from the most recent main branch). Then you can add this file into the `haikus/` directory again and be sure to commit only the `Inital_moon.md` file. If you are working to learn Git, you can also try the rebasing method, which I outline in this tutorial: https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request

2020-10-18 00:31 UTC, ltagliaferri requested changes
Thanks for updating, the second haiku, `coding.md` is still in this pull request. You can take a look at this [Stack Overflow question about changing a file in a PR](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request), or the official docs about [ondoing things](https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things) so that you can unstage `coding.md`. Thank you!

2020-10-20 00:22 UTC, Lucatake commented
Hello, I've tryied in another pull request: https://github.com/do-community/cloud_haiku/pull/1073

2020-10-20 00:49 UTC, Lucatake commented
ok, thank you! I've tryied here now: https://github.com/do-community/cloud_haiku/pull/1153

2020-10-20 00:49 UTC, closed without merging