added new haiku cloud_in_the_sky
do-community/cloud_haiku pull request #967
Opened 2020-10-13 05:44 UTC by hhelenxu

2020-10-16 22:58 UTC, ltagliaferri requested changes
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

2020-10-17 00:13 UTC, hhelenxu commented
Should be fixed now! Thank you!

2020-10-18 02:26 UTC, ltagliaferri approved these changes

2020-10-18 02:26 UTC, ltagliaferri commented
Looks good, thank you for working on this, and thank you for being a part of open source 🎉

2020-10-18 02:27 UTC, merged