Added Moonlit Sea haiku
do-community/cloud_haiku pull request #974
Opened 2020-10-13 08:56 UTC by devruji

My second haiku from me with HacktoberFEST2020

2020-10-16 23:05 UTC, ltagliaferri requested changes
Hi @devruji — I wanted to let you know that if you are submitting this pull request you are granting the copyright under the MIT license. If you do not want the haiku to be part of the terms of our license ([view the license in the main directory of the repo](https://github.com/do-community/cloud_haiku/blob/master/LICENSE)) then please don't submit a pull request to us. If you are comfortable with the open source license, then please remove the note on the haiku. We close inactive pull requests after a few days. Thank you

2020-10-17 07:01 UTC, devruji commented
Hi @ltagliaferri I already updated my Haiku and read to understand already about the license.

2020-10-18 02:28 UTC, ltagliaferri approved these changes

2020-10-18 02:28 UTC, ltagliaferri commented
Awesome, thank you for taking the time to read the license and for being a part of open source!

2020-10-18 02:28 UTC, merged